//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YomukoCore.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YomukoCore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ベースフォルダと同期を行っています に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BookListSyncingBaseFolder {
            get {
                return ResourceManager.GetString("BookListSyncingBaseFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ▲ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColumnOrderAsc {
            get {
                return ResourceManager.GetString("ColumnOrderAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ▼ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColumnOrderDesc {
            get {
                return ResourceManager.GetString("ColumnOrderDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ベースフォルダが見つかりません。設定を確認して下さい
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorBookListBaseFolderNotFound {
            get {
                return ResourceManager.GetString("ErrorBookListBaseFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は見つかりませんでした に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorFileNotFound {
            get {
                return ResourceManager.GetString("ErrorFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルが見つかりませんでした
        ///リストから削除しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorFileNotFoundDelete {
            get {
                return ResourceManager.GetString("ErrorFileNotFoundDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}はすでに存在します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMoveExists {
            get {
                return ResourceManager.GetString("ErrorMoveExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}が見つからないため、コピーできませんでした に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMoveFileNotFound {
            get {
                return ResourceManager.GetString("ErrorMoveFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイトルを抽出できませんでした に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorSearchTitleError {
            get {
                return ResourceManager.GetString("ErrorSearchTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイトルを変更する場合、置き換え前文字列を必ず指定してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorSelectChangeReplaceStringNotFound {
            get {
                return ResourceManager.GetString("ErrorSelectChangeReplaceStringNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   お気に入り に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Favorite {
            get {
                return ResourceManager.GetString("Favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ＜全て＞ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GroupAll {
            get {
                return ResourceManager.GetString("GroupAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル名には必ずTitleが必要です。タイトルを自動的に追加します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InfoAutoAddedTitle {
            get {
                return ResourceManager.GetString("InfoAutoAddedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}をタイトルに設定しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InfoDetailListIsSetTitle {
            get {
                return ResourceManager.GetString("InfoDetailListIsSetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リストから削除します
        ///ファイルも削除する場合は「はい」を選択してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InfoIsDeleteBook {
            get {
                return ResourceManager.GetString("InfoIsDeleteBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルはすでに存在します。上書きしますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InfoMoveExistsWhatsOverride {
            get {
                return ResourceManager.GetString("InfoMoveExistsWhatsOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}冊 / 計:{1}冊 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイトル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] yomuko {
            get {
                object obj = ResourceManager.GetObject("yomuko", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
